trigger:
  branches:
    include:
      - main  # Trigger pipeline for changes to the "main" branch

pool:
  vmImage: 'ubuntu-latest'  # Use Ubuntu as the build agent

variables:
  NODE_VERSION: '16.x'  # Regular variable for Node.js version

steps:
- task: UseNode@2  # Install Node.js
  inputs:
    version: '$(NODE_VERSION)'

- script: |
    echo "Installing dependencies..."
    npm install
  displayName: 'Install Dependencies'

- script: |
    echo "Running tests..."
    npm test
  displayName: 'Run Tests'

- task: CopyFiles@2  # Copy files for deployment
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1  # Publish artifacts
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'java-service-connection'  # Name of the service connection
    appName: 'MyJavaApp'
    package: '$(Build.ArtifactStagingDirectory)/java-app.jar'

- script: |
    echo "Deploying application..."
    # Insert deployment script or commands here
  displayName: 'Deploy Application'
