trigger:
  branches:
    include:
      - main  # Trigger pipeline for changes to the "main" branch

pool:
  vmImage: 'ubuntu-latest'  # Use Ubuntu as the build agent

variables:
  NODE_VERSION: '16.x'  # Node.js version
  appName: 'MyJavaApp'  # Application name

steps:
- task: NodeTool@0  # Correct task for setting up Node.js
  inputs:
    versionSpec: '$(NODE_VERSION)'  # Using the variable for Node.js version
    checkLatest: true

- script: |
    echo "Installing dependencies..."
    npm install
  displayName: 'Install Dependencies'

- script: |
    echo "Running tests..."
    npm test
  displayName: 'Run Tests'

- task: CopyFiles@2  # Copy files for deployment
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1  # Publish artifacts
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'

- task: AzureWebApp@1  # Deploy using the service connection
  inputs:
    azureSubscription: 'java-service-connection'  # Service connection name
    appName: $(appName)
    package: '$(Build.ArtifactStagingDirectory)/java-app.jar'

- script: |
    echo "Deploying application..."
    # Deployment logic can go here
  displayName: 'Deploy Application'
